# Generated by Django 2.0.2 on 2018-03-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('cap_rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
