# Generated by Django 2.0.2 on 2018-03-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteCalculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='adminis',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='marketing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='payroll',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='repairs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='unit_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='utility',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cap_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
