# Generated by Django 2.0.2 on 2018-03-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteCalculator', '0002_auto_20180330_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='adminis',
            new_name='administration',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='monthly_rent',
            new_name='annualTotal',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='unit_number',
            new_name='unitNumber',
        ),
        migrations.AddField(
            model_name='quote',
            name='management',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='monthlyRent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
